# Generated by Django 3.2 on 2023-02-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230205_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('year', 'name'), 'verbose_name': 'Title', 'verbose_name_plural': 'Titles'},
        ),
    ]
